local keymap = vim.keymap.set
local opts = { noremap = true, silent = false }

keymap('n', '<leader>rr', ':source % <CR>', opts)
keymap('n', '<leader>S', ':%s/<c-r><c-w>//g<left><left>', opts)
keymap('n', 'k', "v:count == 0 ? 'gk' : 'k'", { expr = true }, opts)
keymap('n', 'j', "v:count == 0 ? 'gj' : 'j'", { expr = true }, opts)
keymap('n', '<Down>', ':resize -5<CR>', opts)
keymap('n', '<Up>', ':resize +5<CR>', opts)
keymap('n', '<Left>', ':vertical resize -5<CR>', opts)
keymap('n', '<Right>', ':vertical resize +5<CR>', opts)
keymap('n', '<C-k>', '<cmd>bnext<CR>', opts)
keymap('n', '<C-j>', '<cmd>bprevious<CR>', opts)
keymap('n', '<A-h>', '<C-w>h', opts)
keymap('n', '<A-j>', '<C-w>j', opts)
keymap('n', '<A-k>', '<C-w>k', opts)
keymap('n', '<A-l>', '<C-w>l', opts)
keymap('n', '<leader><space>', ':set hlsearch!<CR>', opts)
keymap('n', '<leader>ca', 'ggVGy', opts)
keymap('n', '<leader>d', ':bdelete<CR>', opts)
keymap('n', '<leader>ss', ':HopWord<CR>', opts)
keymap('n', '<leader>nd', ':!rm -rf note.md<CR>', opts)
keymap('n', '<leader>no', ':e note.md<CR>', opts)
keymap('n', '<leader>x', ':q<CR>', opts)
keymap('n', '<leader>X', ':qa<CR>', opts)
keymap('n', '<leader>w', ':w<CR>', opts)
keymap('n', '<leader>W', ':wa<CR>', opts)
keymap('n', '<leader>u', ':ma ', opts)
keymap('n', '<leader>h', ':vert help ', opts)
keymap('n', '<leader>n', ':Lazy<CR>', opts)
keymap('x', '<', '<gv', opts)
keymap('x', '>', '>gv', opts)
keymap('x', 'J', ":move '>+1<CR>gv-gv", opts)
keymap('x', 'K', ":move '<-2<CR>gv-gv", opts)
keymap('i', 'kk', '<Esc>', opts)
