local options = { noremap = true, silent = true }

local function keymap(mode, lhs, rhs, opts)
  opts = opts or options
  vim.keymap.set(mode, lhs, rhs, opts)
end

keymap("n", "<leader>rr", ":source % <CR>")
keymap("n", "<F2>", ":%s/\\s*$//<CR>")
keymap("n", "k", "v:count == 0 ? 'gk' : 'k'", { expr = true })
keymap("n", "j", "v:count == 0 ? 'gj' : 'j'", { expr = true })
keymap("x", "<", "<gv")
keymap("x", ">", ">gv")
keymap("x", "J", ":move '>+1<CR>gv-gv")
keymap("x", "K", ":move '<-2<CR>gv-gv")
keymap("i", "kk", "<Esc>")
keymap("n", "<Down>", ":resize -5<CR>")
keymap("n", "<Up>", ":resize +5<CR>")
keymap("n", "<Left>", ":vertical resize -5<CR>")
keymap("n", "<Right>", ":vertical resize +5<CR>")
keymap("n", "<C-h>", "<cmd>tabprevious<CR>")
keymap("n", "<C-l>", "<cmd>tabnext<CR>")
keymap("n", "<C-k>", "<cmd>bnext<CR>")
keymap("n", "<C-j>", "<cmd>bprevious<CR>")
keymap("i", "<A-h>", "<C-\\><C-n><C-w>h")
keymap("i", "<A-j>", "<C-\\><C-n><C-w>j")
keymap("i", "<A-k>", "<C-\\><C-n><C-w>k")
keymap("i", "<A-l>", "<C-\\><C-n><C-w>l")
keymap("n", "<A-h>", "<C-w>h")
keymap("n", "<A-j>", "<C-w>j")
keymap("n", "<A-k>", "<C-w>k")
keymap("n", "<A-l>", "<C-w>l")
keymap("n", "<leader><space>", ":set hlsearch!<CR>")
keymap("n", "<leader>,", ":Glow<CR>")
keymap("n", "<leader>ca", "ggVGy")
keymap("n", "<leader>bb", ":buffers<CR>")
keymap("n", "<leader>bg", ":buff ")
keymap("n", "<leader>bd", ":b#<bar>bd#<CR>")
keymap("n", "<leader>d", ":bdelete<CR>")
keymap("n", "<leader>h", ":HopWord<CR>")
keymap("n", "<leader>nd", ":!rm -rf note.md<CR>")
keymap("n", "<leader>no", ":e note.md<CR>")
keymap("n", "<leader>o", ":Octo actions<CR>")
keymap("n", "<leader>ry", ":RubyRun<CR>")
keymap("n", "<leader>tt", "<cmd>tabnew<CR>")
keymap("n", "<leader>tc", "<cmd>tabclose<CR>")
keymap("n", "<leader>td", "<cmd>tabdo<CR>")
keymap("n", "<leader>tp", "<cmd>tabprevious<CR>")
keymap("n", "<leader>tn", "<cmd>tabnext<CR>")
keymap("n", "<leader>x", ":q<CR>")
keymap("n", "<leader>X", ":qa<CR>")
keymap("n", "<leader>w", ":w<CR>")
keymap("n", "<leader>W", ":wa<CR>")
keymap("n", "<leader>y", ":Emmet ")
keymap("n", "<C-n>", ":Explore!<CR>")
